### ISSUE TITLE
NextCloudにExporterを入れる

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#107]
- [ ] Node exporter
- [ ] ダッシュボードを作成する
- [ ] PrometheusからScrapeする設定

--- 
- ディスク容量
- ネットワークトラフィック
- CPU/メモリ使用率
---
- 既存のdocker-composeとは別に作成する

**Comment by inductor** [comment]
https://github.com/xperimental/nextcloud-exporter こんなのもあるのね
