### ISSUE TITLE
OBSの残作業

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#113]
- [x] 具体的なシーン設定を作成する
- [x] Advanced Scene Switcherの構成
- [ ] 各シーンのテスト

**Comment by TakumaNakagame** [comment]
プレイベントでの気付き

「動画のループ → 5分後にシーン切り替え」ができないと思ってたが、できる
と思っていたが、うまいこと動かなかった。（無限ループ動画はNGだったぽい）

---

リハーサルの時点で出来ている内容
- 動画 → 幕間の流れはOK
- シーンなどの名前などは、概ね変えた（漏れあるかも）

**Comment by Gaku-Kunimi** [comment]
> プレイベントでの気付き

>「動画のループ → 5分後にシーン切り替え」ができないと思ってたが、できる
> と思っていたが、うまいこと動かなかった。（無限ループ動画はNGだったぽい）

Sequence タブがそれにあたるが、 無限ループシーンからは抜け出せず (正確に言うと一瞬シーン遷移するけど戻される)
https://cloudnativedays.slack.com/archives/C0204MGK6V6/p1644941387154269

**Comment by Gaku-Kunimi** [comment]
シーンの組み方メモ
- 休憩
- カウントダウン
- 動画(事前録画の場合) or NDI ソース

Advanced Scene Switcher
- Trigger は Media タブのみ。以下の遷移を自動化する
  - カウントダウン -> 動画
  - 動画 -> 幕間

トランジションについて
- トランジションオーバーライドを使って、動画orリモート登壇シーンは `カット` にしておく
- 基本はカスタムのトランジションをいれた `スティンガー`
