### ISSUE TITLE
事前収録動画の準備

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#119]
- [x] 動画一件差し替え
- [x] 動画のダウンロード
- [x] ~~m3u8への変換~~ https://github.com/cloudnativedaysjp/broadcast/issues/121 に移管
  - ~~ffmpeg で音量差修正と同時に行う~~

- [x] 音量差を修正する
  - カウントダウン動画と並べてみて問題ないかを確認
- [x] S3 にアップロード & セッション ID のディレクトリを作成
- [x] NextCloudにアップロードしたら、 @TakumaNakagame に連絡する（当日のバックアップ用SSDにコピーしておく

**Comment by Gaku-Kunimi** [comment]
方針

以下のいずれか
- MediaEncoder でラウドネス正規化
- ry さんが作ってくれた FFMpeg スクリプトを使う https://github.com/cloudnativedaysjp/dreamkast-broadcast/tree/main/media-converter

**Comment by TakumaNakagame** [comment]
>  動画のダウンロード
動画自体はダウンロード可能な状態

>  m3u8への変換
以下のファイルを使えばコンバートできるけど、めっちゃ高い（今回は4万円くらいかかりそう
https://github.com/cloudnativedaysjp/broadcast/tree/main/aws-mediaconvert

対し、ffmpegを使う場合は、アウトプットにm3u8を指定できるので、これを使うのが良さそう
https://nico-lab.net/hls_muxer_with_ffmpeg/

**Comment by Gaku-Kunimi** [comment]
GPU 付きの VM を借りて ↓ を試すのがベストな気がしてる
https://gist.github.com/maitrungduc1410/1768ce3b369bf04a229ab043201c7197
