### ISSUE TITLE
当日やることリスト

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#122]
- [ ] OBS動作テスト (https://github.com/cloudnativedaysjp/dreamkast-broadcast/issues/113)
- [ ] 当日用Discord VCへの参加
- [ ] オープニング・クロージング用の機材配置（ https://github.com/cloudnativedaysjp/broadcast/issues/123 ）
- [ ] NextCloud を終了している
- [ ] スタジオモードになっている
- [ ] NDI ソースの大きさがキャンバスサイズに合っている
- [x] m3u8 が dreamkast に登録されている

**Comment by Gaku-Kunimi** [comment]
- advanced scene switcher の挙動が怪しいので、 vlc で countdown と session を組む方法に戻す
  - countdown と session を vlc ソースで組み合わせる
  - mediaソースを消す
  - フィルタでスケーリングフィルタを基本的にはつけておく
  - トランジションオーバーライドを未設定に戻す
  - 動画終了時に蓋絵に遷移するように下のレイヤーに画像として蓋絵を配置

**Comment by Gaku-Kunimi** [comment]
windows update を 7日間停止する

**Comment by Gaku-Kunimi** [comment]
OBS の設定で、チェックを入れる
-  確認ダイアログを表示する 系の3つ
- 配信開始時に録画開始

**Comment by Gaku-Kunimi** [comment]
配信前チェックリスト
- [ ]  NextCloud を終了している
- [ ]  スタジオモードになっている
- [ ]  NDI ソースの大きさがキャンバスサイズに合っている
