### ISSUE TITLE
Broadcast用のGoogle Driveフォルダを作成する

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#129]
現状、各イベントごとにフォルダを作っているが、これでは辛いので横断的に使えるやつを作成する。
Dkは @jacopen が管理しているので、それを踏襲して同じように作ってもらう

**Comment by jacopen** [comment]
作成完了。
リンクはこちら

https://drive.google.com/drive/folders/1yMzEkceXgN9aBq5JBIDpRe5pZ2GPW3E0?usp=sharing

CNSec2022のフォルダにショートカットも作成済み
