### ISSUE TITLE
事前収録動画の自動チェックの仕組みを作る

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#134]
### チェック内容
- 解像度が適切か
- アスペクト比が適切か
- フォーマットが適切か

**Comment by tanayan299** [comment]
解像度とアスペクト比が適切かを判定して出力するスクリプトを作成。(https://github.com/cloudnativedaysjp/broadcast/commit/4e011866d201e3f8b68b48806c48639df95c2d89)

Inputソースとしては ディレクトリ/ファイル どちらでも。

動画の情報は`ffprobe`から取得し、動画ごとに以下の情報をJSON出力する。
```
"file_name": チェック対象の動画ファイル名
"resolution_status": OK/NG（デフォルトの判定基準と合致するか）
"resolution_type":  SD/HD/FullHD/WQHD/4K（合致しない場合は`NON STANDARD`）
"aspect_status": OK/NG（デフォルトの判定基準と合致するか）
"aspect_ratio": 判定アスペクト比（合致しない場合は動画のサイズ）
```

どこか（例えばSlack）に結果を通知する仕組みなどは別枠で。

**Comment by TakumaNakagame** [comment]
## 正常時
1. CSVをもとにしてNextcloudのディレクトリを参照する
2. 動画が存在する場合、タイムスタンプが最も新しい動画を対象とする
3. 対象の動画をチェックする
4. チェックしたら動画のファイル名を固定する（session.mp4とか）
5. 結果をDkにPutする

## 固定ファイル名でアップロードされた場合
`session(1).mp4`とかに自動で書き換えられるので問題なし
