### ISSUE TITLE
OBSの設定を投入する仕組みを作る

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#135]
OBS Websocketを利用して設定を投入する仕組みを作る
当初、以下のIssueで設定jsonを自動生成するものを検討したが、こちらではリアルタイムに変更が加えられなかったり、設定ファイルのスキーマに追従しないといけない。

対し、OBS Websocketであれば、比較的このあたりの問題が解消されているのでよさそう。
なお、最初にOBS Websocketのプラグインを入れたり、これを有効化するためには設定jsonを予め投入しておく必要がある。

1. 初期化処理： 特定のJSONを読み込み
2. OBS Websocketによって設定を投入

**Comment by TakumaNakagame** [comment]
さらに、これを利用して自動的にシーンを変更するような仕組みもあると良さそう

**Comment by Gaku-Kunimi** [comment]
CSVから生成して、冪等になるようなものを python など慣れた言語で作り、そのあと js で websocket を扱うライブラリに移行し dk の管理画面に融合できると嬉しい

**Comment by Gaku-Kunimi** [comment]
cnsec までに作りたい内容
CSV をもとに 普段手動オペレーションで作っていたシーンコレクション(↓)を作成する(すべて収録動画という前提で)

1. シーンコレクション
    1. 時間とタイトルを読んでシーン名を構築
    2. ソースを追加
        1. 登壇シーン
            1. vlc
                1. 共通カウントダウン動画
                2. 登壇動画
            2. 動画終了後画像
            3. リモート登壇ソース
        2. 休憩シーン
            1. vlc ソース(ループON)
                1. 幕間 ❎ 2
                2. 幕間 PR 
                3. CM ディレクトリ
        3. 調整中
            1. メディアソース(ループON)
                1. 調整中動画
        5. 待機ループ
            1. vlc ソース(ループON)
                1. 幕間 ❎ 2
                2. 幕間 PR

**Comment by TakumaNakagame** [comment]
状況
- シーンの作成は完了した
- シーンの中身はこれから

**Comment by Gaku-Kunimi** [comment]
7/29 夜 ~ 7/30 (土) で出来るところまでやる

**Comment by Gaku-Kunimi** [comment]
https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#createsceneitem が理解できれば、ソースの追加が自動化出来ると見込んでいるが、まだ深堀り出来ていない

**Comment by Gaku-Kunimi** [comment]
GetInputSettings でパラメータの入れ方を取得して、 CreateInput の inputSettings に指定して作っていく形だった。 

https://github.com/cloudnativedaysjp/broadcast/tree/main/obs-websocket#memo-%E3%82%BD%E3%83%BC%E3%82%B9-input-%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B

**Comment by Gaku-Kunimi** [comment]
当日までに対応しないといけない点

- [ ] スラッシュをアンダーバーに置き換えないと CI/CD みたいなタイトルで、ディレクトリ名が想定と変わってしまう
- [ ] フィルターで HD 画質を救うために、 vlc には全部アスペクト比フィルターを突っ込む
- [ ] テロップ, Twitter の設置
- [ ] https://github.com/cloudnativedaysjp/broadcast/issues/174

- [ ] out of index してる幕間  (closing の直前と、ありがとうございましたの直前)

**Comment by Gaku-Kunimi** [comment]
電光掲示板は Linux 版の OBS のテキスト(FreeType2)が、 Windows 版の GDI+ に対して古いので、文字に背景色とかが付けれない ため、見た目がよくなくてあきらめた

トランジションとボイスは明日の朝げんきだったら
