### ISSUE TITLE
シーンの自動スイッチング

### ISSUE THREAD

**Issue by Gaku-Kunimi** [cloudnativedaysjp/broadcast#137]
related: #135 
websocket 経由で自動スイッチングする仕組み。

できて欲しい
- 録画動画のみのセッションを完全自動でスイッチングする
- #135 と連携してセッション情報は CSV から読む

cnsec 以降でもいいので、できるとうれしい
- 手動スイッチングのトラックに合わせて10 分遅れで始めるなども対応できるように

使えそうなライブラリ
- [https://github.com/Elektordi/obs-websocket-py/blob/master/samples/switch_scenes.py](https://github.com/Elektordi/obs-websocket-py/blob/master/samples/switch_scenes.py) 
    - シーンの取得
    - シーン名を指定して移動
    - イベントを取得などが出来る

**Comment by TakumaNakagame** [comment]
- CSV/APIをもとに時間で発火する仕組みはできている
- ↑を延長させて実際に動くようにする
- +αでブラウザを使って操作する仕組みを検討中
