### ISSUE TITLE
CfP受付Nextcloud用のインスタンスを作成する

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#139]
以下の内容で作成をお願いします

- CPU: 4Core
- Mem: 4GB以上
- ディスク: 250GB

他のインスタンスと同じように初期化してもらいつつ、シュッとできるならDocker/Composeのインストールもお願いしたいです。
面倒なら手動でやるのでそれでもOK

また、これはご相談になりますが、登壇者に公開するDNS名をきめたいのですが、なにか候補はありますか？
私は、`upload.cnsec2022.cloudnativedays.jp`とかが良さそうかなと思ったり。

**Comment by jacopen** [comment]
イベント名がついたサブドメインは紛らわしいため作らない方針なので
`uploader.cloudnativedays.jp`
でいきます

**Comment by jacopen** [comment]
@TakumaNakagame 完了ー

**Comment by jacopen** [comment]
ふと思ったけど公開するならLet's Encryptで証明書の発行と設定が必要だね

**Comment by TakumaNakagame** [comment]
対応ありがとうございます！

> ふと思ったけど公開するならLet's Encryptで証明書の発行と設定が必要だね

さくらのクラウドのエンハンスドロードバランサでSSL終端できるので、それでやりましょう。
tf側での対応ってお願いできますか？

**Comment by jacopen** [comment]
@TakumaNakagame 既存のProviderではEnhanced LBに未対応な感じがする

**Comment by TakumaNakagame** [comment]
こちらで対応されています🙋
https://docs.usacloud.jp/terraform/r/proxylb/

証明書は以下にて、Letsを定義できます
https://docs.usacloud.jp/terraform/r/proxylb_acme/

**Comment by jacopen** [comment]
Enhanced LBの作成は完了。ただこれを通すとNextcloud周りの動きが怪しい･･･

**Comment by jacopen** [comment]
LB設定まで終わったので終了！
