### ISSUE TITLE
7/16 リハ向け情報

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/broadcast#147]
# Staging Dreamkast

https://staging.dev.cloudnativedays.jp/

### Room1
https://streamyard.com/yyg2igj63q

### Room2
https://streamyard.com/4hze9yqtsg

### TrackA

rtmp://44.208.67.90:1935/yporuvhaxe/yjmfintcrd

### TrackB

rtmp://67.202.27.215:1935/kylcgdmtab/ufebkmdial

### TrackC

rtmp://44.205.161.117:1935/poezsyrxfq/hbmiuotrvk

## 各トラック m3u8

https://www.hlsplayer.net/

### TrackA

https://294fdb0f5e90.us-east-1.playback.live-video.net/api/video/v1/us-east-1.607167088920.channel.ReSjIfyRr8Jy.m3u8

### TrackB

https://294fdb0f5e90.us-east-1.playback.live-video.net/api/video/v1/us-east-1.607167088920.channel.wdz9y50mby2o.m3u8

### TrackC

https://294fdb0f5e90.us-east-1.playback.live-video.net/api/video/v1/us-east-1.607167088920.channel.2gqzyZMdApfp.m3u8

**Comment by tsukaman** [comment]
ざっくりSYオペレータ操作
- 開始前
  - 登壇者/アテンドの両名がそろい次第配信に追加
    - アテンドから登壇者への説明
  - 配信2分前にアテンドが登壇者にもう間もなく開始の通知
  - 配信1分前にアテンドが「カウントダウン始まります」を登壇者に伝えた後、カウントダウン動画開始
- 終了時
  - 登壇者が発表を終えたら、無音の蓋動画を流す
  - OBS側の切り替え完了報告をもらったら、アテンドを配信に追加し蓋動画を外す

**Comment by tsukaman** [comment]
- 開始前
  - ゲストログインURLより担当のSYスタジオにログイン
    - "CNSecスタッフ"の名前でログインする
  - オペレータがスピーカと一緒にステージにあげるのを待機する
  - ステージに上がったら、スピーカーに案内と確認を行う
    - マイク、カメラ（カメラなしも可）、画面共有の確認
    - 流れの説明（アテンドからスピーカーへ以下の内容を伝える）
      - 「開始2分前に声をかけます。」
      - 「1分前からカウントダウン動画が流れます。」（ここで自動マイクミュート＆スタッフが抜ける）
      - 「以降の会話はプライベートチャットで行います。」
      - 「カウントダウン終了後、音楽が消えたら話し始めてください。」
        - 1画面しかなくてSYの画面が見れない場合は、音楽消えたタイミングを契機に開始してもらう
      - 「画面の切り替えはオペレーターで行いますので操作は不要です（自動でスライド画面になる）。」
      - 「登壇終了後は、オペレーターが配信切り替えを行います。切り替え完了まで画像や音声が配信されてますのでご注意ください。」
      - 「配信切り替え後にアテンドが入室しご挨拶させて頂きますので、退室せずにおまちください。」
  - 配信2分前までに上記の確認と説明を終了させる
  - 配信2分前に通知が近藤さんからあるので「2分前です。間もなく始まります。」とスピーカーに伝える
  - 配信1分前に通知が近藤さんからあるので「1分前です。カウントダウン始まります。以降はプライベートチャットで会話をお願いします」」とスピーカーに伝える。
- 登壇中
  - オペレーターと協力し、配信に問題がないかを可能な範囲で確認する
    - 別デバイスが用意できるのであればDreamkast配信もチェックできると尚良い
- 終了時
  - オペレータがステージにあげるのを待機する（OBSの配信切り替え後にステージにあげてくれる）
  - ステージにあがったら、スピーカーにお礼を伝え、退室してもらう

**Comment by jacopen** [comment]
- Secondary IPの設定を自動化したい
- Switch周りのプラン見直し
- nginxのDocker compose設定を自動化
- nginxのDocker Engine自動化
- Monitoring用のUIをDkUIに生やす
