### ISSUE TITLE
機材の調達を検討する

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#151]
- PC x 4
  - スタンダートスペック
- トランシーバー x5～
  - リモ部屋 x2 x2
  - 近藤さん指示用 x1
  - 予備
- ディスプレイ（24インチ程度） x4

**Comment by TakumaNakagame** [comment]
リモ部屋には、リモ部屋のディスプレイにDkを表示して状況を把握したい
→ 雑なスタンダートスペックなPCが2台ほしい

**Comment by TakumaNakagame** [comment]
OBS操作PC
- 動画の修正はがくくんの自前を利用し、オペレーションは調達PCを使うと良さそう
- 画面としては3トラック分ほしい（ = PCが3台というわけではない
- 雑なスタンダートスペックPCがx2 + ディスプレイx4

**Comment by KaseiKondo** [comment]
@TakumaNakagame 上記承知いたしました！
