### ISSUE TITLE
スタッフロールを作る

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#155]

**Comment by TakumaNakagame** [comment]
8割がたOKそうなので、特に問題なし

**Comment by jacopen** [comment]
完成版ここに設置しましたー
内容確認したらこのIssueはクローズでお願いします @TakumaNakagame 

https://nextcloud2.cloudnativedays.jp/f/59672

**Comment by TakumaNakagame** [comment]
ありがとうございます、めっちゃいい感じです
これで行きましょうか。Closeしちゃいます
