### ISSUE TITLE
リモ部屋の対応手順をまとめる

### ISSUE THREAD

**Issue by tsukaman** [cloudnativedaysjp/broadcast#159]
- [x] Opの作業内容をまとめる
- [x] Atの作業内容をまとめる
- [x] トラブル発生時の対応をまとめる

**Comment by tanayan299** [comment]
@tsukaman 
Op側（+α）こんな感じでいかが？

---
### ログイン方法
1. https://streamyard.com/ にアクセス
2. ログインで dreamkast01@gafa.co.jp にアクセス
3. 飛んできたメールに記載の番号を入力してAdminログイン

### 初めに確認すること
- 入っている部屋を間違えていないか、Operator/Attendでダブルチェック
- 配信のレイアウトが、「画面レイアウト」になっていることを確認
- 動画の「連続再生」にチェックが入っていないことを確認する

### セッション開始時
- Speaker/Attend の両名がそろい次第、配信上に追加する（両名のマイクがミュートでないことを確認する）
  - Attend から Speaker へ各種案内
    - カメラ/マイク/画面共有の確認とチェック
    - セッション開始前/終了後の案内
- 近藤さんから、トランシーバー経由でセッション開始 2分前の案内を受ける
  - Attend から Speaker へセッション開始前2分前の旨、1分前になるとカウントダウン動画が開始する旨を通知
  - カウントダウンが始まる前に、スライド資料も配信に上げておく（配信開始時の状態にする）
- 近藤さんから、トランシーバー経由でセッション開始 1分前の案内を受ける
  - Attend から Speaker へカウントダウン動画が始まることを通知
  - Attend の通知を受けて、カウントダウン動画を開始する
  - Attend を配信から除外する
    - 念のため、動画が「連続再生」になっていないことを確認する
    - OBS側は、別室でSYをモニタしており、動画の開始に合わせてOBSの切り替えを行う
- セッション開始時、Speaker がミュートになっていないことを念のため確認する

### セッション中
- Attendと協力し、配信に問題がないかを可能な範囲で確認する
  - 別デバイスが用意できるのであれば Dreamkast 配信もチェックできると尚良い

### セッション終了時
- Speaker のセッションが終了後、無音の蓋動画を再生する
- 近藤さんから、OBS側の切り替え完了報告を受ける
  - 蓋動画を外し、Attend がミュートになっていないことを確認したうえで配信に追加する

### オンライン登壇者が落ちた時の対応 ([#147](https://github.com/cloudnativedaysjp/broadcast/issues/157))
#### 問題発生時
- SY の Operator/Attend が登壇者が落ちたことを検知する（一番配信側に近い）
  - Operator が 無音の蓋動画を流す
  - Operator が 近藤さんにトランシーバー経由で連絡を行う
- 登壇者フォロー
  - Attend が上記と並行し、Slack経由で Speaker のフォローを行う
- 調整中シーンへの切り替え
  - 近藤さんからの指示を受け、OBS側で調整中シーンへ切り替えを行う
- 視聴者への連絡
  - 問題発生をDk上のチャットで連絡（現地対応）

#### 復旧時
- 全体で調整の上復帰するため、各コンポーネント勝手に復旧はしない
  - OBS側で調整シーンを解除する
  - SY側で蓋動画を外す

**Comment by tsukaman** [comment]
対応手順をスプレッドシートにまとめました

https://docs.google.com/spreadsheets/d/114HMIg0E8MKza7lpRluofSMa1pR3wiaD1Nu-T-dNSJE/edit#gid=607100263
