### ISSUE TITLE
NextCloud: ファイルをダウンロードできない

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/broadcast#161]
スピーカーから問い合わせがあり、前倒しで動画をダウンロードして確認しようとしたところ、下記のエラーが発生しました。
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/31978147/180577330-342ece41-d90b-43b5-9c78-b57dd882bea7.png">

[該当のセッション](https://cloudnativedays.slack.com/archives/C03KH3FT823/p1658481027181999?thread_ts=1658451208.628189&cid=C03KH3FT823)だけでなく、他の動画も試してみましたが、すべてエラーになりました。
また当然ブラウザ上での再生もできません。
すみませんが、ご確認・対応をお願いできますか？:bow:

**Comment by TakumaNakagame** [comment]
![image](https://user-images.githubusercontent.com/5129906/180586132-1b8b54e3-0d66-4cf9-bdce-883283961f59.png)

**Comment by TakumaNakagame** [comment]
https://uploader.cloudnativedays.jp/apps/files/?dir=/cnsec2022/1436_%E3%81%AA%E3%81%9C%E3%81%82%E3%81%AA%E3%81%9F%E3%81%AE%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%AEDevSecOps%E3%81%AF%E5%BD%A2%E9%AA%B8%E5%8C%96%E3%81%99%E3%82%8B%E3%81%AE%E3%81%8B&openfile=3036

**Comment by TakumaNakagame** [comment]
解決

原因は、自動チェックバッチによるリネームによって、Nextcloud側のDBと不整合が発生したため。
これを解消するため、`./occ groupfolder:scan`コマンドを実行して、フォルダの再スキャンを行ったら解消した

実行コマンド↓
`docker-compose exec -u www-data app ./occ groupfolder:scan 1`

**Comment by nabemasat** [comment]
@TakumaNakagame ダウンロードできるようになりました！ありがとうございます！
