### ISSUE TITLE
NextCloud 1442がダウンロードできない

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/broadcast#164]
@TakumaNakagame 
度々ですみません。1442 Takaya Ideさんの動画について、ダウンロードできなくなっています。
ご確認をお願いできますか:bow:
<img width="957" alt="image" src="https://user-images.githubusercontent.com/31978147/181402262-94c7352f-7202-4f75-8de3-3238b9e7b43b.png">

※同時期にアップロードされた1438 Chihiro Hasegawaさんのセッションはダウンロードできました。

**Comment by TakumaNakagame** [comment]
ご迷惑おかけします:bow:
こちら対応完了しました

**Comment by nabemasat** [comment]
ありがとうございます！ダウンロードできました！
