### ISSUE TITLE
クロージング枠の対応

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#174]
- StreamYardからクロージング配信
- クロージングが終わったらエンドロールシーンへ切り替え
- エンドロールシーンの背景に白ベースの「CNDTもよろしく！」な画像をはめ込んでおく
- エンドロールが終了したら背景が表示され、そのまま数分放置後、配信を終了する

**Comment by TakumaNakagame** [comment]
背景画像は @jacopen さんが作る

**Comment by jacopen** [comment]
背景画像はこちらに格納済み
https://nextcloud2.cloudnativedays.jp/f/60501

**Comment by Gaku-Kunimi** [comment]
エンドロールが終了したら背景が表示され、そのまま数分放置後、配信を終了する 

これ音が無音になってしまって悲しいので、 `Observability Conference 2022は終了しました` シーンに BGM とともに画像を表示するようにした

エンドロール動画の z-common 格納待ち `EndCredit.mp4` 想定
