### ISSUE TITLE
GPUインスタンスの制限について確認する

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#182]
最低必要数： 6VM

- [ ] 上限解放できるか確認する
- [ ] AWSをつかう場合のケースを試算する
- [ ] AWSと比較して安くできるか確認する

**Comment by jacopen** [comment]
過去にAWSでSwitcherVM上げたときのCFnが残っていた。
https://github.com/cloudnativedaysjp/broadcast/blob/main/cloudformation/ec2.yaml#L17

g4dn.xlargeのVMに100GBのボリュームをくっつけていたようだ。


AWS計算機で簡易に見積もり。
- g4dn.xlarge + 100GBを6台、延べ10日動かす
- t3.smallを2台(RTMP受け)、延べ10日動かす
動かしていない時間は止める

という条件で12,288.60 USDとなった。これにネットワークの転送料が追加される感じ。


![image](https://user-images.githubusercontent.com/79102/186656191-72bac52f-f2c2-4b3c-92f7-aded31b240f9.png)
