### ISSUE TITLE
Nextcloudインスタンスに裏LANを通す

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#194]
以下の通り、Nextcloudで同期しているとき、Nextcloudからの上りが100Mbpsの頭打ちを受けているようにみえる。
※オブジェクトストレージのダウンロードは、実質無制限なので影響は少なそう

これを改善するために、Nextcloudも裏LANを通し、裏LAN経由で同期することでより広帯域で同期することが期待できる。

![image](https://user-images.githubusercontent.com/5129906/189511665-1bea84ba-9a40-4d46-b099-6b3239b2fdfe.png)

### 対象
- nextcloud2
- uploader

**Comment by TakumaNakagame** [comment]
VM側は対応済みなので、OS側からIPの設定等を実施する

**Comment by jacopen** [comment]
nextcloud2でens4として認識済み
![image](https://user-images.githubusercontent.com/79102/193016530-2c8a4511-3ac2-4ec5-a378-9daa80c1bbee.png)

**Comment by TakumaNakagame** [comment]
後段作業として、OBS側の設定変更（メディアソースの参照先を変更する）

**Comment by TakumaNakagame** [comment]
- [ ] uploaderにNICの追加 @jacopen 
- [ ] nextcloud2, uploaderのNICの設定 @TakumaNakagame 
- [ ] Switcher01 - 03 Nextcloudクライアントの設定変更 @TakumaNakagame 
- [ ] Switcher04 のNextcloudクライアントの設定変更 @Gaku-Kunimi

**Comment by TakumaNakagame** [comment]
Uploader: 192.168.71.112
nextcloud2: 192.168.71.111
