### ISSUE TITLE
CNDT2022 プレイベントでテストしたいこと（放映形式）を決める

### ISSUE THREAD

**Issue by tsukaman** [cloudnativedaysjp/broadcast#199]
以下の点を検討/決定して、Contentsチームのプレイベント企画チームに共有する

- 何トラックで運営するか？
- 同時間帯におけるリアルタイム登壇と事前収録の数
- 必要な運用スタッフの数（事務局とも要連携）

その他、プレイベントコンテンツ（企画）やタイムテーブルの決定に関連しそうなものがあれば、共有する。

**Comment by TakumaNakagame** [comment]
ユーザ向けに見せたいものを挙げると良さそう

### やりたいこと（希望
- ハイブリッド打ち上げの検証
  - 登壇者は身内が良さそう
  - 日付は未定
  - 10月24日の週あたり（10月31～4日くらい？
  - 人が揃うならやる、揃わないならやらない
  - 占有時間：  18時～22時ごろ
- オンライン枠の対応（本番で対応する人を回すと良さそう？
  - PK1としてはやりたいので、やりましょう → 外部の人にお願いする決定
