### ISSUE TITLE
Observability環境の作成

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#205]
- [x] TerraformでVMを作成する（4コア8GB 100GB） @jacopen 
- [x] ELKスタックの作成 @ijokarumawak 
- [x] SSO 設定 @ijokarumawak 
- [x] 監視設定等の追加 @ijokarumawak

**Comment by jacopen** [comment]
@ijokarumawak 

VM作成終わりました。

`ssh ubuntu@elk.cloudnativedays.jp` で繋がるはず

**Comment by ijokarumawak** [comment]
cloudnativedays.jp のユーザーなら Kibana にアクセスできるように SSO 設定完了しました。
Elastic stack のライセンスは無償のベーシックなので、 SAML も OIDC も使えず... 無理やり Nginx (Restify) + Vouch で Auth0 のロールに追随する SSO 実装しました...!

https://elk.cloudnativedays.jp/kibana/
からアクセスできます。

**Comment by jacopen** [comment]
@ijokarumawak ありがとうございます！
今試してみたんですが502 Bad Gatewayが出ちゃうようです

**Comment by ijokarumawak** [comment]
@jacopen 確認いただきありがとうございます！なんでしょう、キャッシュですかね
私の環境では再現しないので、他の方にも確認をお願いしてみます

**Comment by ijokarumawak** [comment]
@jacopen 他の方に確認していただいたところ、502 は発生せず、Kibana の画面が見えているようです
一度キャッシュクリアして再度ご確認いただけますか?
