### ISSUE TITLE
ドキュメント作成リスト

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#213]
## プレイベント関連
- [x] オンライン登壇オペレーション関連
    - [x] SY Operator向け
    - [x] SY Attend向け
- [x] 全体進行表
    - [x] 現地登壇
    - [x] オンライン登壇
    - [x] 事前収録

## 本番
- [ ] 当日のEMTECスイッチングオペレーション
- [ ] 全体進行表
    - [ ] 現地登壇
    - [x] オンライン登壇
    - [ ] 事前収録
- [ ] PK1スタッフ向け
    - [ ] ブイキューブ

**Comment by tsukaman** [comment]
関連Issueのスピーカー向けビジュアルガイドは、Attend役の人の説明負担を軽減する目的で作成する。

**Comment by tsukaman** [comment]
プレイベント向けに作成した。
- [CNDT2022 プレイベント スピーカーガイド](https://docs.google.com/presentation/d/1JI7MIYY2jKA-XERgmwfdjmXVmamM868adIufhAiQBq0/edit?usp=sharing)
