### ISSUE TITLE
Streamyardの準備

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#217]
- [x] ブランド素材の用意
- [x] 枠の用意
- [x] 配信先の設定
- [x] カウントダウン動画
- [x] プラン変更（当日）

**Comment by tsukaman** [comment]
@TakumaNakagame こちら、先ほど口頭でもお願いしましたが、接続テストやドキュメント作成の為にも使える部屋をご準備頂けますでしょうか？

可能なら、今日/明日中くらいには頂きたいです・・・

**Comment by TakumaNakagame** [comment]
以下で作成しました（というかCNsecのものそのまま利用しました）
https://streamyard.com/z8i2bwprp7

**Comment by TakumaNakagame** [comment]
@tsukaman 以下で作成しました（というかCNsecのものそのまま利用しました）
https://streamyard.com/z8i2bwprp7

**Comment by TakumaNakagame** [comment]
カウントダウン動画は、前日18時頃に作ってもらう
作成したら、OBSとStreamyardに反映する
