### ISSUE TITLE
プレイベント向け事前収録動画のアップロードURLを発行する

### ISSUE THREAD

**Issue by tsukaman** [cloudnativedaysjp/broadcast#225]
プレイベントの事前収録者向けにアップロードURLを用意する。対象は2名。

**Comment by TakumaNakagame** [comment]
2000_Feature 環境の自動生成と B_G Deployment で 効率的かつ安全なリリースプロセスを構築 にファイルをアップロード
https://uploader.cloudnativedays.jp/s/kQ9LPm7a9WmKEY8

2001_ソフトウェアエンジニアにとってサステナブルなIaCを 実現するための取り組み にファイルをアップロード
https://uploader.cloudnativedays.jp/s/rbWxK8o2Tyt6Q3K

**Comment by nabemasat** [comment]
@TakumaNakagame 
tichimuraさんの「クラウドのスケールメリットと地理的特性をデータベースにも活かしましょう」も事前収録なので、アップローダーをご用意いただけますか:bow:
https://cloudnativedays.slack.com/archives/C0474955C6M/p1666521660934159?thread_ts=1666420562.973769&cid=C0474955C6M

@tsukaman

**Comment by nabemasat** [comment]
@TakumaNakagame 
すみません、確認したのですが、Kazuki Aizawaさん 「Feature 環境の自動生成と...」は現地登壇をご希望です。https://cloudnativedays.slack.com/archives/C0474955C6M/p1666260723768619?thread_ts=1666235360.647899&cid=C0474955C6M

正しくは、tichimuraさん「クラウドのスケールメリットと地理的特性をデータベースにも活かしましょう」が
事前収録なのですが、アップローダーの記載内容を変更していただけますか:bow:
https://cloudnativedays.slack.com/archives/C0474955C6M/p1666521660934159?thread_ts=1666420562.973769&cid=C0474955C6M

@tsukaman

**Comment by TakumaNakagame** [comment]
@nabemasat  あ！ホントですね
タイムテーブルを見間違えていました。対応しましたので確認お願いします！

**Comment by nabemasat** [comment]
ありがとうございますー。投稿しましたー。
https://cloudnativedays.slack.com/archives/C0474955C6M/p1666604010138329
