### ISSUE TITLE
obsの設定を変更する

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#230]
### タスク
- [x] メディアソース利用時の「ハードウェアデコードの有効化」を追加
- [x] オンライン登壇・現地登壇ではそれぞれメディアソースを使い回す
- [x] Nginxの参照先を裏LANに変更する

### 裏LAN一覧
| 対象 | DNS名 | IP |
| --- | --- | --- |
| nginx01 | local-nginx01.cloudnativedays.jp | 192.168.71.21 |
| nginx02 | local-nginx02.cloudnativedays.jp | 192.168.71.22 |
| nginx03 | local-nginx03.cloudnativedays.jp | 192.168.71.23 |
| nginx04 | local-nginx04.cloudnativedays.jp | 192.168.71.24 |
| nginx05 | local-nginx05.cloudnativedays.jp | 192.168.71.25 |
| nginx06 | local-nginx06.cloudnativedays.jp | 192.168.71.26 |

**Comment by jacopen** [comment]
✅ 裏LANをTerraformで自動設定出来るようにした
✅ 裏DNS名設定完了

**Comment by Gaku-Kunimi** [comment]
スクリプト反映はしていないが、リハ用のシーンではこれらの設定を投入済み
