### ISSUE TITLE
リハーサル向けドキュメント

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#231]
# 開催概要
## 場所
[有明セントラルタワーホール&コンファレンス 3F](https://ariake-hall.jp/access.html)

## 日時
11月06日（日） 09:00 - 21:00
※9時現地集合

## 参加者
https://chouseisan.com/s?h=4490db2f298b4106889f9ae00606b119

# やること
時間 | やること
-- | --
09:00 - 12:00 | 現地配線
12:00 - 13:00 | お昼ごはん
13:00 - 15:00 | リモプロチェック
15:00 - 17:00 | 通しリハ
18:00 - 19:00 | 振り返り
19:00 - 21:00 | バラシ

# 配信情報

## ログイン出来ない各部屋向けm3u8一覧
https://bit.ly/cndt2022m3u8

### Track A
- RTMP
  - rtmp://52.197.58.54:1935/tymcxqorfz/vusxcykjma
- IVS m3u8
  - https://2bfacab657db.ap-northeast-1.playback.live-video.net/api/video/v1/ap-northeast-1.607167088920.channel.SAE92NawzYyD.m3u8

### Track B
- RTMP
  - rtmp://18.176.124.199:1935/chzjrbtxes/kdrwygfahb
- IVS m3u8
  - https://2bfacab657db.ap-northeast-1.playback.live-video.net/api/video/v1/ap-northeast-1.607167088920.channel.wSeXe3dcv4Lq.m3u8
### Track C
- RTMP
  - rtmp://35.73.172.56:1935/ecbgvradyz/ptesyfdkbo
- IVS m3u8
  - https://2bfacab657db.ap-northeast-1.playback.live-video.net/api/video/v1/ap-northeast-1.607167088920.channel.DQ6C15psjA6P.m3u8
### Track D
- RTMP
  - rtmp://35.73.39.172:1935/xgszcqhrmk/lrgzcbmasf
- IVS m3u8
  - https://2bfacab657db.ap-northeast-1.playback.live-video.net/api/video/v1/ap-northeast-1.607167088920.channel.nzbVrLfPOUsS.m3u8
### Track E
- RTMP
  - rtmp://52.69.40.0:1935/voxgifnaty/xfrzdsmcyu
- IVS m3u8
  - https://2bfacab657db.ap-northeast-1.playback.live-video.net/api/video/v1/ap-northeast-1.607167088920.channel.3sDnC2QQc6ZH.m3u8
### Track F
- RTMP
  - rtmp://54.199.145.182:1935/dnaobyeizq/hynfvixtlm
- IVS m3u8
  - https://2bfacab657db.ap-northeast-1.playback.live-video.net/api/video/v1/ap-northeast-1.607167088920.channel.4sNFfbIoRbDc.m3u8

# 備考
- 当日の機材配置は トラックA、C、及びEで実施する
- A/Cは現地登壇、Eはパブリックビューイング
- 負荷テストを実施する際は、B,D,FについてはStreamyardから送信する
  - テストには `Big Buck Bunny` の動画を流す
- オンライン登壇テストは、基本PK1スタッフにおいて行う
- Zello（トランシーバー）の使用についてのアナウンスは行う

**Comment by TakumaNakagame** [comment]
やること
- [ ] https://github.com/cloudnativedaysjp/broadcast/issues/230
- [ ] https://github.com/cloudnativedaysjp/broadcast/issues/220

**Comment by TakumaNakagame** [comment]
- IVSの作成（ステージング環境）
- スイッチの設置（NETGEAR, CISCO）
- PCの設定
    - https://github.com/cloudnativedaysjp/broadcast/issues/96
- A, C部屋の作成
    - 各種機材の設置
    - ケーブル配線
    - ![CND Remote Production v2 0](https://user-images.githubusercontent.com/5129906/200140783-2ed82397-7e15-4298-8025-bc9935dd1c8b.jpg)
- E部屋の作成
    - PCの設置
    - 配線

**Comment by jacopen** [comment]
カメラ向けのMiniHDMIのケーブルが足りない

**Comment by tsuka716** [comment]
ルームAおよびCにおいて、
ATEM miniおよびROLAND V-1HD+のPC接続用USBケーブルが足りない。

- Type-B to Type-A x1
- Type-C to Type-C x1

これが2部屋分必要。

**Comment by tsuka716** [comment]
各ルーム

登壇者PC（演台）からROLAND V-1HD+ppへ接続するための
長いHDMIケーブルが必要。

**Comment by Gaku-Kunimi** [comment]
- キーノート現地登壇3つ -> 事前収録3つ の連続
  - 現地登壇はシーン１つ -> (switcher でスイッチング) -> 事前収録(vlc ソースで連続再生) でよさそう
- 現地登壇のカウントダウンを考慮していなかった
  - Swicher01 とかのシーン構成では、これまで通り rtmp から カウントダウンが来るものだと思ってよさそう
    - カウントダウンを流すのは VR-4HD で出来ないか検証する (現地のスイッチャーが触る機械が一つになる)
      - これが出来ないと OBS でカウントダウンを流すことになる
      - **VR-4HD のプレビュー出力を登壇者にモニターすることで、カウントダウンを登壇者が確認できる**

**Comment by TakumaNakagame** [comment]
A,B はミキサーあり
C,D,はなし
E,Fもなし（使用予定なし）

**Comment by Gaku-Kunimi** [comment]
https://github.com/cloudnativedaysjp/broadcast/issues/230 については
スクリプト反映はしていないが、リハ用のシーンではこれらの設定を投入済み

**Comment by Gaku-Kunimi** [comment]
nginx 裏LAN経由も設定済み

**Comment by tkc66-buzz** [comment]
RolandがUSB接続でOBSと連携できなかった　ため、Swicher経由でHDMIを２本使用して接続する。

**Comment by ijokarumawak** [comment]
会場 IP アドレスから OBS, Nginx に SSH 接続できず、各インスタンスからのメトリック収集設定できない状況。ELK サーバーから Ngix 、OBS インスタンスへの SSH を解放できると。。

**Comment by TakumaNakagame** [comment]
<html>
<body>


ID | Track | Input Name | Input ID | Destination URL | Channel Name | Channel ID | Channel State
-- | -- | -- | -- | -- | -- | -- | --
  | 101 | A | staging_cndt2022_trackA | 6268703 | rtmp://52.197.58.54:1935/tymcxqorfz/vusxcykjma | staging_cndt2022_trackA | 2903028 | RUNNING
  | 100 | B | staging_cndt2022_trackB | 4350943 | rtmp://18.176.124.199:1935/chzjrbtxes/kdrwygfahb | staging_cndt2022_trackB | 8375665 | RUNNING
  | 102 | C | staging_cndt2022_trackC | 3833650 | rtmp://35.73.172.56:1935/ecbgvradyz/ptesyfdkbo | staging_cndt2022_trackC | 9189541 | RUNNING
  | 103 | D | staging_cndt2022_trackD | 694651 | rtmp://35.73.39.172:1935/xgszcqhrmk/lrgzcbmasf | staging_cndt2022_trackD | 2875118 | RUNNING
  | 104 | E | staging_cndt2022_trackE | 4814901 | rtmp://52.69.40.0:1935/voxgifnaty/xfrzdsmcyu | staging_cndt2022_trackE | 9943306 | RUNNING
  | 105 | F | staging_cndt2022_trackF | 5433910 | rtmp://54.199.145.182:1935/dnaobyeizq/hynfvixtlm | staging_cndt2022_trackF | 7708458 | RUNNING


</body>
</html>

**Comment by TakumaNakagame** [comment]
<html>
<body>


ID | Track | Name | ARN | Playback URL
-- | -- | -- | -- | --
  | 94 | A | staging_cndt2022_trackA | arn:aws:ivs:ap-northeast-1:607167088920:channel/SAE92NawzYyD | https://2bfacab657db.ap-northeast-1.playback.live-video.net/api/video/v1/ap-northeast-1.607167088920.channel.SAE92NawzYyD.m3u8
  | 95 | B | staging_cndt2022_trackB | arn:aws:ivs:ap-northeast-1:607167088920:channel/wSeXe3dcv4Lq | https://2bfacab657db.ap-northeast-1.playback.live-video.net/api/video/v1/ap-northeast-1.607167088920.channel.wSeXe3dcv4Lq.m3u8
  | 96 | C | staging_cndt2022_trackC | arn:aws:ivs:ap-northeast-1:607167088920:channel/DQ6C15psjA6P | https://2bfacab657db.ap-northeast-1.playback.live-video.net/api/video/v1/ap-northeast-1.607167088920.channel.DQ6C15psjA6P.m3u8
  | 97 | D | staging_cndt2022_trackD | arn:aws:ivs:ap-northeast-1:607167088920:channel/nzbVrLfPOUsS | https://2bfacab657db.ap-northeast-1.playback.live-video.net/api/video/v1/ap-northeast-1.607167088920.channel.nzbVrLfPOUsS.m3u8
  | 98 | E | staging_cndt2022_trackE | arn:aws:ivs:ap-northeast-1:607167088920:channel/3sDnC2QQc6ZH | https://2bfacab657db.ap-northeast-1.playback.live-video.net/api/video/v1/ap-northeast-1.607167088920.channel.3sDnC2QQc6ZH.m3u8
  | 99 | F | staging_cndt2022_trackF | arn:aws:ivs:ap-northeast-1:607167088920:channel/4sNFfbIoRbDc | https://2bfacab657db.ap-northeast-1.playback.live-video.net/api/video/v1/ap-northeast-1.607167088920.channel.4sNFfbIoRbDc.m3u8


</body>
</html>

**Comment by TakumaNakagame** [comment]
パブリックビューイングのレイテンシがひどいので会場に配線したほうがいいかもしれない

**Comment by TakumaNakagame** [comment]
- OBSがダメ
- RolandがUVC対応じゃない
- カウントダウン動画の再生方法

**Comment by TakumaNakagame** [comment]
Room1、見切れてる

![20221106_184144.JPG](https://user-images.githubusercontent.com/5129906/200163987-2cabaa10-cb68-49c4-b145-0d9527c9e737.JPG)

**Comment by jacopen** [comment]
PV用マシンはスクリーンセーバーに入らないように設定必須

**Comment by ijokarumawak** [comment]
OBS のログを 01 - 06 まで収集するようにしました。
switcher05 だけエラーメッセージっぽいのがたくさん出ていました

```
05
[NULL @ 0x7f54542c29c0] reference count 1 overflow
18:51:10.000
switcher05
[NULL @ 0x7f54542c29c0] reference count 1 overflow
18:51:10.000
switcher05
[NULL @ 0x7f544c2d74c0] reference count 1 overflow
18:51:10.000
switcher05
[h264 @ 0x7f544ddc3440] reference count overflow
18:51:10.000
switcher05
[h264 @ 0x7f544ddc3440] decode_slice_header error
18:51:10.000
switcher05
[h264 @ 0x7f544ddc3440] no frame!
18:51:11.000
switcher05
[NULL @ 0x7f54542c29c0] reference count 1 overflow
18:51:11.000
switcher05
[NULL @ 0x7f544c2d74c0] reference count 1 overflow
18:51:11.000
switcher05
[h264 @ 0x7f544c0278c0] reference count overflow
18:51:11.000
switcher05
[h264 @ 0x7f544c0278c0] decode_slice_header error
```
とか
```

[h264 @ 0x7f544c022a80] number of reference frames (0+5) exceeds max (4; probably corrupt input), discarding one
18:53:46.000
switcher05
[h264 @ 0x7f544c022a80] top block unavailable for requested intra mode -1
18:53:46.000
switcher05
[h264 @ 0x7f544c022a80] error while decoding MB 0 0, bytestream 21022
18:53:46.000
switcher05
[h264 @ 0x7f544c01d240] number of reference frames (0+5) exceeds max (4; probably corrupt input), discarding one
18:53:46.000
switcher05
[NULL @ 0x7f544c2d74c0] reference count 3 overflow
18:53:46.000
switcher05
[h264 @ 0x7f544c01d240] top block unavailable for requested intra mode -1
18:53:46.000
switcher05
[h264 @ 0x7f544c01d240] error while decoding MB 0 0, bytestream 18072
18:53:46.000
switcher05
[h264 @ 0x7f544d117cc0] number of reference frames (0+5) exceeds max (4; probably corrupt input), discarding one
18:53:47.000
switcher05
[h264 @ 0x7f544d117cc0] top block unavailable for requested intra mode -1
18:53:47.000
switcher05
[h264 @ 0x7f544d117cc0] error while decoding MB 0 0, bytestream 16162
18:53:47.000
switcher05
[h264 @ 0x7f544ddc3440] number of reference frames (0+5) exceeds max (4; probably corrupt input), discarding one
18:53:47.000
switcher05
[NULL @ 0x7f54542c29c0] reference count 3 overflow
18:53:47.000
switcher05
[h264 @ 0x7f544ddc3440] top block unavailable for requested intra mode -1
18:53:47.000
switcher05
[h264 @ 0x7f544ddc3440] error while decoding MB 0 0, bytestream 21527
```
とか

**Comment by TakumaNakagame** [comment]
OBSをエンコーダとして使えないので、代わりにstreamyardを利用した

**Comment by TakumaNakagame** [comment]
キーノートのとき、C/EにてPinPで映像が写っていた

**Comment by TakumaNakagame** [comment]
TrackAの配信用PCでスクリーンセーバーが表示された

**Comment by TakumaNakagame** [comment]
ふたえの設定が必要

**Comment by TakumaNakagame** [comment]
登壇者の顔が暗い

**Comment by TakumaNakagame** [comment]
各部屋や動画によって音量差が激しい。
卓で音量を調整する必要がある

**Comment by TakumaNakagame** [comment]
> OBS のログを 01 - 06 まで収集するようにしました。 switcher05 だけエラーメッセージっぽいのがたくさん出ていました
> 
> ```
> 05
> [NULL @ 0x7f54542c29c0] reference count 1 overflow
> 18:51:10.000
> switcher05
> [NULL @ 0x7f54542c29c0] reference count 1 overflow
> 18:51:10.000
> switcher05
> [NULL @ 0x7f544c2d74c0] reference count 1 overflow
> 18:51:10.000
> switcher05
> [h264 @ 0x7f544ddc3440] reference count overflow
> 18:51:10.000
> switcher05
> [h264 @ 0x7f544ddc3440] decode_slice_header error
> 18:51:10.000
> switcher05
> [h264 @ 0x7f544ddc3440] no frame!
> 18:51:11.000
> switcher05
> [NULL @ 0x7f54542c29c0] reference count 1 overflow
> 18:51:11.000
> switcher05
> [NULL @ 0x7f544c2d74c0] reference count 1 overflow
> 18:51:11.000
> switcher05
> [h264 @ 0x7f544c0278c0] reference count overflow
> 18:51:11.000
> switcher05
> [h264 @ 0x7f544c0278c0] decode_slice_header error
> ```
> 
> とか
> 
> ```
> 
> [h264 @ 0x7f544c022a80] number of reference frames (0+5) exceeds max (4; probably corrupt input), discarding one
> 18:53:46.000
> switcher05
> [h264 @ 0x7f544c022a80] top block unavailable for requested intra mode -1
> 18:53:46.000
> switcher05
> [h264 @ 0x7f544c022a80] error while decoding MB 0 0, bytestream 21022
> 18:53:46.000
> switcher05
> [h264 @ 0x7f544c01d240] number of reference frames (0+5) exceeds max (4; probably corrupt input), discarding one
> 18:53:46.000
> switcher05
> [NULL @ 0x7f544c2d74c0] reference count 3 overflow
> 18:53:46.000
> switcher05
> [h264 @ 0x7f544c01d240] top block unavailable for requested intra mode -1
> 18:53:46.000
> switcher05
> [h264 @ 0x7f544c01d240] error while decoding MB 0 0, bytestream 18072
> 18:53:46.000
> switcher05
> [h264 @ 0x7f544d117cc0] number of reference frames (0+5) exceeds max (4; probably corrupt input), discarding one
> 18:53:47.000
> switcher05
> [h264 @ 0x7f544d117cc0] top block unavailable for requested intra mode -1
> 18:53:47.000
> switcher05
> [h264 @ 0x7f544d117cc0] error while decoding MB 0 0, bytestream 16162
> 18:53:47.000
> switcher05
> [h264 @ 0x7f544ddc3440] number of reference frames (0+5) exceeds max (4; probably corrupt input), discarding one
> 18:53:47.000
> switcher05
> [NULL @ 0x7f54542c29c0] reference count 3 overflow
> 18:53:47.000
> switcher05
> [h264 @ 0x7f544ddc3440] top block unavailable for requested intra mode -1
> 18:53:47.000
> switcher05
> [h264 @ 0x7f544ddc3440] error while decoding MB 0 0, bytestream 21527
> ```
> 
> とか

映像自体は特に問題は感じなかった（そもそもPinPになったりとかはあった
