### ISSUE TITLE
uploaderの作り直しをする

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#232]

**Comment by TakumaNakagame** [comment]
memo 
現状では、Generalグループに含まれるアカウントのみがグループフォルダにアクセスできる。
しかし、本来であれば各チームごとに設定を変更するべきであるため、Generalを使った運用は誤りである。

作り直すときは、これを適切に変更する

**Comment by jacopen** [comment]
こちらも再作成完了
