### ISSUE TITLE
ebpfの動画を追加で結合する

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#244]
keynoteのebpfの動画について、動画を追加することになる。
動画は11/16頃までに提出してもらえるため、これを受け取ったら以下の処理を行う

- [x] 既存の動画と結合する
- [ ] 結合した動画を @MasayaAoyama に確認してもらう
- [ ] 問題なければuploaderにアップロードしなおしてリネーム処理をする

ref
https://cloudnativedays.slack.com/archives/C03UK1VNG4A/p1668058760433409?thread_ts=1668058760.433409&cid=C03UK1VNG4A

**Comment by MasayaAoyama** [comment]
動画はこちらで！
本編の前ににくっつけていただければOKです！
https://drive.google.com/file/d/1gs8F489PXVDR_YfhOk28FMaKmXerEjrX/view?usp=share_link

**Comment by TakumaNakagame** [comment]
@MasayaAoyama 遅くなりました。
以下で編集しました。ご確認をお願いします。
https://uploader.cloudnativedays.jp/f/13137

**Comment by TakumaNakagame** [comment]
@MasayaAoyama 改めて、動画を編集したのでご確認をお願いします。

https://uploader.cloudnativedays.jp/f/13332

なお、以下の点を変更しています。

- リップシンクの対応
- 切り替え時に、カメラなしのスライドタイトルだけを表示
    - 本編が、冒頭映像がなく、音声のみだったのでこの対応
    - スライドはタイトルは、動画から画像を抽出し、カメラ画像を削除しました。
      本来のスライドとは異なるかもしれませんが、こちらのほうが自然なので、こちらでOKとしていただけると助かります。
