### ISSUE TITLE
幕間動画とイベント情報幕間動画(cmの後に流れているやつ) の作成

### ISSUE THREAD

**Issue by Gaku-Kunimi** [cloudnativedaysjp/broadcast#246]
いつものやつを作る
- UPCOMING を talk_id にリネームしてレンダリング
- みどころスライドから抜粋したイベント情報&スポンサー(最新版か確認)
- 会場 Map (new!)
- 夜イベ導線スライド (Day1 のみ new!)

- [ ] ~~Day 2 向け動画も出力しておき、 Day1 終了後には 夜イベ導線スライドを外した動画に差し替える~~
- [x] day1 A~E
- [x] day1 F Track (14トラック対応)
- [ ] day2

**Comment by TakumaNakagame** [comment]
土曜日には…！

**Comment by Gaku-Kunimi** [comment]
p5. スポンサー +  p11. Ovservability + スタンプラリーからアンケートくらいの５枚 を使う 
https://docs.google.com/presentation/d/1M-9ByZkVjnU6PAXcpUCijw_TqALSvKzeVbqd-PSgGVA/edit#slide=id.p

https://github.com/cloudnativedaysjp/broadcast/issues/207 のコメントから引用
」
