### ISSUE TITLE
Uploaderにあげている動画は、イベントごとに別の場所に退避する

### ISSUE THREAD

**Issue by tanayan299** [cloudnativedaysjp/broadcast#253]
イベントごとの事前収録動画をずっとUploader VMに保持しておくと、VMのディスク容量が死ぬ。
なので、イベント終了後にイベントで使用した事前収録動画をどこか（S3？）に退避する。

手動で退避、動画チェックの際に最新ファイルをS3に投げつける、など。

**Comment by TakumaNakagame** [comment]
CNDT2022について`cndt2022-movies` バケットに退避済み

今後については、イベント終わるごとに `EVENTNAME-movies` バケットに手動で退避する。
