### ISSUE TITLE
VCubeさんにQR 蓋絵画像をお渡しする。オペレーションをインプットする 

### ISSUE THREAD

**Issue by Gaku-Kunimi** [cloudnativedaysjp/broadcast#254]
- QR 蓋絵画像は 青山さんに依頼済み　https://cloudnativedays.slack.com/archives/C0204MGK6V6/p1668701022471749?thread_ts=1668700673.849519&cid=C0204MGK6V6　
- 画像化して、セッション終了後に 2分ほど蓋絵として表示してもらう点を VCube さんに共有
- E, F トラックの運用は、 PV 用 PC画面で、QRのウインドウを最前面に表示するような運用にするので、当日誰が動かすかを調整する
- 
![image](https://user-images.githubusercontent.com/25493569/202497611-11f5f723-bb13-4bc1-b35c-71404c63b971.png)

**Comment by MasayaAoyama** [comment]
作成doneです！
https://docs.google.com/presentation/d/1M-9ByZkVjnU6PAXcpUCijw_TqALSvKzeVbqd-PSgGVA/edit#slide=id.g18f8d665ee2_0_34
