### ISSUE TITLE
前日準備について

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#261]
## 参加者
https://chouseisan.com/s?h=4490db2f298b4106889f9ae00606b119

## スケジュール

時間 | 内容
-- | --
09:00 | 集合
09:00 - 09:30 | ブリーフィング
09:30 - 12:00 | 部屋設営
12:00 - 13:00 | お昼
13:00 - 13:30 | ブリーフィング
13:30 - 14:30 | 部屋ごとテスト
14:30 - 15:30 | リハーサル1
15:30 - 16:00 | ブリーフィング
16:00 - 18:00 | リハーサル2
18:00 - 18:30 | ブリーフィング
18:30 - 21:00 | 予備

## やること
- 環境構築
- 現地登壇オペレーションの確認
- 全体の流れリハーサル・確認・ブラッシュアップ
- 昼休憩コンテンツの準備

#### トラックA-D
- [ ] ブイキューブさんによる現地登壇構成
- [ ] ネットワークは、有線LANを壁から2本引く（スイッチングハブを利用）
- [ ] OBS PCにバックアッププラン用のデータを仕込み

#### トラックE,F
- [ ] リモート登壇用構成を作成（PCの設置）
- [ ] ネットワークは、有線LANを壁から2本引く（スイッチングハブを利用）
- [ ] OBS PCにバックアッププラン用のデータを仕込み

#### Room3（配信部屋・事務局）
- [ ] 机配置
- [ ] モニタリング用モニタの設置
- [ ] Discord端末・スピーカーマイクの設置

## 確認事項
- [ ] [録画の有無](https://github.com/cloudnativedaysjp/broadcast/issues/257)
- [ ] 会場の無線LAN状況（主にスタッフが使うWi-Fi）
- [ ] 当日、ブイキューブスタッフさんがお昼取るタイミング・場所ある？

**Comment by TakumaNakagame** [comment]
### @Gaku-Kunimi 
- 幕間のレンダリング D-E
- スイッチャーの構成
- Fの幕間がダミーになる

### @capsmalt 
- 今日のPC用にcndctlの構成を作る

### @tanayan299 
- ツールの習熟

### @ijokarumawak 
- cndctl
- 新しいスイッチャーに monitoring の設定を入れる

### @tkc66-buzz 
- cndctl

**Comment by tanayan299** [comment]
Switcher 01, Switcher 03は強制停止実施

**Comment by TakumaNakagame** [comment]
18:34 時点の課題

- PVの音と現地の音声が混線してしまう at vcube
- StreamyardにQRを乗せる話 at remote
  - 現地で乗せればいいので、Streamyardではロゴ蓋画を乗せれば良い
    - アナウンスは後回しで良い
  - 終わったあと、アナウンスや登壇者へのお礼のお言葉が配信に流れてしまう
    - 鍋島さんに入ってもらう
- Broadcastチームの負荷
  - 2トラック分のOBSを操作している
  - 問題が発生した場合、片系のOBSの操作が疎かになる
  - →モニタの枚数を減らす
  - →かめねこが緊急時に入る
  - Broadcastチームから各部屋に投げる話
