### ISSUE TITLE
ブイキューブ向けドキュメント

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#264]
## OBSの設定

- [ ] 配信
    - [ ] サービス： `カスタム`
    - [ ] サーバー・シークレットキー： 下記表を参照
- [ ] 出力
    - [ ] 映像ビットレート： `6000`
    - [ ] エンコーダ： `ハードウェア（QSV, H264）`
- [ ] 音声
    - [ ] グローバル音声デバイス
        - [ ] デスクトップ音声： `無効`
        - [ ] マイク音声： `無効`
- [ ] 映像
    - [ ] 出力（スケーリング）解像度： `1920x1080`

| track | サーバ | ストリームキー |
| --- | --- | --- |
| A | `rtmp://nginx01.cloudnativedays.jp:10003/live` | `cndt2022-studio-a`  |
| B | `rtmp://nginx02.cloudnativedays.jp:10003/live` | `cndt2022-studio-b`  |
| C | `rtmp://nginx03.cloudnativedays.jp:10003/live` | `cndt2022-studio-c`  |
| D | `rtmp://nginx04.cloudnativedays.jp:10003/live` | `cndt2022-studio-d`  |

## パブリックビューイングPCの接続先 (リハ)

| track | 接続先 | 
| --- | --- | 
| A | `https://2bfacab657db.ap-northeast-1.playback.live-video.net/api/video/v1/ap-northeast-1.607167088920.channel.SAE92NawzYyD.m3u8` | 
| B | `https://2bfacab657db.ap-northeast-1.playback.live-video.net/api/video/v1/ap-northeast-1.607167088920.channel.wSeXe3dcv4Lq.m3u8` | 
| C | `https://2bfacab657db.ap-northeast-1.playback.live-video.net/api/video/v1/ap-northeast-1.607167088920.channel.DQ6C15psjA6P.m3u8` | 
| D | `https://2bfacab657db.ap-northeast-1.playback.live-video.net/api/video/v1/ap-northeast-1.607167088920.channel.nzbVrLfPOUsS.m3u8` | 

## パブリックビューイングPCの接続先 (production)

| track | 接続先 | 
| --- | --- | 
| A | `https://2bfacab657db.ap-northeast-1.playback.live-video.net/api/video/v1/ap-northeast-1.607167088920.channel.HLYr7vmDT9BY.m3u8` | 
| B | `https://2bfacab657db.ap-northeast-1.playback.live-video.net/api/video/v1/ap-northeast-1.607167088920.channel.ervq4uZ7MVPR.m3u8` | 
| C | `https://2bfacab657db.ap-northeast-1.playback.live-video.net/api/video/v1/ap-northeast-1.607167088920.channel.qXxnA8stmXSC.m3u8` | 
| D | `https://2bfacab657db.ap-northeast-1.playback.live-video.net/api/video/v1/ap-northeast-1.607167088920.channel.qcGM9et2zEoC.m3u8` |

**Comment by capsmalt** [comment]
https://github.com/cloudnativedaysjp/broadcast/issues/278

Day1_13:20-18:00
================================
TrackA:
name: 1602_フロントエンド開発に集中するためのクラウドネイティブ環境を使おう
duration(s): "2417.314900"

name: 1543_Google Kubernetes Engine (GKE) で実現する運用レスな世界
duration(s): "2397.066667"

================================
TrackB:
name: 1530_PostgreSQLとApache Kafkaのマルチクラウド環境をワンクリックで構築
duration(s): "2349.113433"

name: 1538_実践！クラウドネイティブセキュリティ- スクウェア・エニックスが進めるコンテナ化への旅
duration(s): "2460.720000"

================================
TrackC:
name: 1555_旅するCSO 鈴木いっぺいの「KubeCon現地リキャップ」
duration(s): "2365.760000"

name: 1542_クラウドネイティブ環境を数時間で作成できる『テクマトリックスNEO』
duration(s): "2246.240000"

================================
TrackD:
name: 1553_Self-Hosted Runners & Actions Runner Controller (ARC)を運用すること
duration(s): "2244.640000"

name: 1598_NTTデータ流コスト効率術 _ モノリス vs マイクロサービス vs MuleSoft
duration(s): "2366.265320"

================================
TrackE:
name: 1512_目で見て体験！ Kubernetesのしくみ
duration(s): "2432.266667"

name: 1540_クラウドネイティブエンジニアの育成について実践していること
duration(s): "2303.666667"

name: 1536_はじめよう Kubernetes PersistentVolume のバックアップ
duration(s): "2338.520000"

name: 1594_100%クラウドベースのデジタル体験基盤(DXP)開発フロー
duration(s): "2085.566667"

================================
TrackF:
name: 1518_バッチシステムをクラウドネイティブにするために考えたこと
duration(s): "1186.057000"

name: 1570_入門: Knative Serving + Kubernetes Gateway APIで構築するクラウドネイティブな汎用サーバーレス環境
duration(s): "973.072100"

name: 1549_NGINX Ingress Controllerで実現するKubernetesアプリケーションのセキュリティ対策
duration(s): "1995.033300"

name: 1509_脱・塩漬け！サステナブルなKubernetesエコシステムの管理をしていくために
duration(s): "1080.041000"

name: 1576_いにしえのエンプラ情シスが内製化ではなくアーキテクトの「手の内化」を推進した話
duration(s): "1117.560000"

name: 1607_フロントエンド・オブザーバビリティ
duration(s): "2371.880000"

name: 1556_k8s Operatorで運用負担減&ハイブリッドクラウドのコスト最適化をした話
duration(s): "1170.936433"

name: 1557_実例から学ぶ Kubernetes Custom Controller のステータス管理
duration(s): "1231.280000"

**Comment by capsmalt** [comment]
Day2
========================
TrackA:
name: 1599_CI_CDの次はCO-継続した最適化 !
duration(s): "2307.204900"

name: 1519_Ingress Controller for LINE Private Cloud Platform
duration(s): "2136.400000"

========================
TrackB:
name: 1597_【対談】HashiCorp×TED -インフラのクラウドシフトを促進する最新機能とクラウドネイティブなマルチベンダー連携事例-
duration(s): "2483.666667"

name: 1529_〈ログ監視の常識を覆す〉オブザーバビリティ―の最前線！！
duration(s): "2056.042000"

========================
TrackC:
name: 1544_PagerDutyで始めるAIOps − AIと自動化でインシデント対応をモダン化する
duration(s): "2316.647667"

name: 1605_最新のクラウドネイティブアーキテクチャに対応したセキュリティソリューションPrisma Cloudのご紹介
duration(s): "1174.900000"

========================
TrackD:
name: 1522_モヤモヤをスッキリ、理解の点と点を繋げて、コンテナセキュリティを得意分野に！
duration(s): "2239.800000"

name: 1606_AWS_Azure_GCP環境とKubernetesのバックアップならVeeamです
duration(s): "2596.209319"

========================
TrackE:
name: 1541_リアルタイム分析サービスをクラウドネイティブDB (TiDB) で作るとこうなる
duration(s): "2202.720000"

name: 1550_Scalar DB: Cloud-native Transaction Manager
duration(s): "2511.785000"

========================
TrackF:
name: 1560_ペパボのSREが生産性の向上を目指しCloud Nativeなチーム作り実践した話
duration(s): "1267.400000"

name: 1558_しきい値監視からの卒業！ Prometheus による機械学習を用いた異常検知アラートの実装
duration(s): "1259.640000"

name: 1551_GitLab流コラボレーションスタイル 〜DevOpsプラットフォームとSSOTで実現する「エンジニアのハッピーライフ」〜
duration(s): "2038.040000"

name: 1571_実践！OpenTelemetry と OSS を使った Observability 基盤の構築
duration(s): "1247.040000"

name: 1583_はじめてのDapr on Kubernetes～分散システムでの一過性の障害に備える
duration(s): "1200.000000"

name: 1565_【既存アプリをコンテナ化したいのじゃが】-Kubernetesへリフトする開発者が乗り越える壁-
duration(s): "2413.828083"
