### ISSUE TITLE
OBSソースの設定変更

### ISSUE THREAD

**Issue by capsmalt** [cloudnativedaysjp/broadcast#265]
@TakumaNakagame 

- [ ] VLC ビデオのソースで再生を再開する的なチェックがついている

- [ ] 調整中シーン入れる
- [ ] メディアソース
  - [ ] ネットワークバッファ: 2MB -> 0MB に変更
  - [ ] 利用可能な場合はハードウェアデコードを使用する: チェック入れる
- [ ] キーノート間の休憩シーンを入れる
- [ ] キーノートのポート番号が 10002 になっているが、他のAのセッションは 10003 で後者にそろえたい
- [ ] VLCビデオソース
  - [ ] プレイリストをループ再生: チェック外す

- [ ] 休憩シーン(幕間): シーン追加
  - [ ] 休憩シーンの talk_id ベースで参照されているが、 エンコード都合で 幕間が示すセッションの talk_id.mp4 を参照するようにしたい
- [ ]  多分) シーンの一番下に引くロゴ画像
- [ ]  開始前の CM をカット
- [ ]  開始前に エモスライドショーを入れる https://nextcloud2.cloudnativedays.jp/f/121631
- [ ]  エンドロール
- [ ]  終了後画像シーン
- [ ]  B~F のキーノート中の幕間が {Aトラックで流れるキーノートのtalk_id}.mp4 で問題ないか確認
- [ ]  (間に合えば) カスタムトランジション
- [ ] nginx01~06 が 全部 nginx01 を見ている
- [ ] AのKeynote時は、各トラックはAのm3u8をメディアソースで参照する
  - [ ] `https://2bfacab657db.ap-northeast-1.playback.live-video.net/api/video/v1/ap-northeast-1.607167088920.channel.SAE92NawzYyD.m3u8`

**Comment by Gaku-Kunimi** [comment]
https://github.com/cloudnativedaysjp/broadcast/issues/259 から拾ってくる
