### ISSUE TITLE
Zoom Rooms -> OBSでNDI入力した際、画像と音声のズレが発生することがある。

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/broadcast#72]
10/24の検証で発覚。

Zoom Rooms からNDI経由でOBSに入力した際、モニターすると画像と音声がはっきり分かるレベルでズレていた。
しかしながら、実際に配信されている動画ではそこまでズレていなかったり、OBSを再起動するとズレが解消されたケースもあった。

挙動が読めないが、違和感を覚えるレベルの遅延は解消したいので、対処方法を検討する

**Comment by Gaku-Kunimi** [comment]
ズレ確認用動画
http://twitch-event-engineering-public.s3.amazonaws.com/sync-footage/Sync-Footage-V1-H264.mp4

**Comment by Gaku-Kunimi** [comment]
[ndi遅延検証会2021-12-05 05_38_23 PM からスキャン.pdf](https://github.com/cloudnativedaysjp/dreamkast-broadcast/files/7655548/ndi.2021-12-05.05_38_23.PM.pdf)

**Comment by TakumaNakagame** [comment]
o11y2022でも再現
