### ISSUE TITLE
当日準備関連

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/broadcast#98]
- [ ] 動画データを入れたUSBメモリを作成する

## 動画データを入れたUSBメモリを作成する
基本的にはNextCloudでSyncさせる予定だが、万が一Syncが終わらないなどの問題があった場合のバックアップとして利用する。
@TakumaNakagame は各種録画データ等を、 @Gaku-Kunimi は幕間動画などを持っていく。

**Comment by Gaku-Kunimi** [comment]
会場設営に買っておきたいもの

- [ ] 養生テープ
- [ ] マッキー
- [ ] 付箋

**Comment by Gaku-Kunimi** [comment]
リハ時にセットアップできていないマシン
- [ ] remote-zoom-04 
- [ ] broadcast-montoring

**Comment by jacopen** [comment]
さくらインターネットをツールスポンサーに
